# Generated by Django 4.2.3 on 2023-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_categoria_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
