# Generated by Django 4.2.3 on 2023-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='maquinas',
            field=models.ManyToManyField(to='biblioteca.maquina'),
        ),
    ]
